"""Generate tenant.tfvars HCL from form data for each environment."""

from __future__ import annotations

from typing import Any

from src.models.form_schema import CAPACITY_TIERS, MODEL_FAMILIES
from src.models.tenant import TenantFormData

# Environment-specific overrides
ENV_DEFAULTS: dict[str, dict[str, Any]] = {
    "dev": {
        "environment_tag": "dev",
        "soft_delete_retention_days": 7,
        "replication_type": "LRS",
        "geo_redundant_backup": False,
        "log_retention_days": 30,
    },
    "test": {
        "environment_tag": "test",
        "soft_delete_retention_days": 30,
        "replication_type": "LRS",
        "geo_redundant_backup": False,
        "log_retention_days": 30,
    },
    "prod": {
        "environment_tag": "prod",
        "soft_delete_retention_days": 90,
        "replication_type": "LRS",
        "geo_redundant_backup": False,
        "log_retention_days": 90,
    },
}


def generate_all_env_tfvars(data: TenantFormData) -> dict[str, str]:
    """Generate tfvars for all three environments from a single form submission."""
    return {env: _generate_tfvars(data, env) for env in ("dev", "test", "prod")}


def _generate_tfvars(data: TenantFormData, env: str) -> str:
    """Generate a single tenant.tfvars HCL string for the given environment."""
    defaults = ENV_DEFAULTS[env]
    env_label = env.upper()

    model_deployments = _build_model_deployments(data.model_families, data.capacity_tier)
    admin_block = _build_user_management(data.admin_emails)

    lines = [
        f"# =============================================================================",
        f"# TENANT: {data.display_name} - {env_label} ENVIRONMENT",
        f"# =============================================================================",
        f"# {env_label} environment configuration for {data.display_name}.",
        f"# Generated by Tenant Onboarding Portal.",
        f"# =============================================================================",
        f"",
        f'tenant = {{',
        f'  tenant_name  = "{data.project_name}"',
        f'  display_name = "{data.display_name}"',
        f'  enabled      = true',
        f"",
        f"  # PE subnet assignment — sticky, do not change after first deploy (destroys/recreates all PEs)",
        f'  # Valid keys: privateendpoints-subnet, privateendpoints-subnet-1, privateendpoints-subnet-2, ...',
        f'  pe_subnet_key = "privateendpoints-subnet"',
        f"",
        f"  tags = {{",
        f'    ministry    = "{data.ministry}"',
        f'    environment = "{defaults["environment_tag"]}"',
    ]
    if data.department:
        lines.append(f'    department  = "{data.department}"')
    lines += [
        f"  }}",
        f"",
        _key_vault_block(data.key_vault_enabled, defaults),
        "",
        _storage_account_block(data.storage_account_enabled, defaults, env),
        "",
        _ai_search_block(data.ai_search_enabled),
        "",
        _cosmos_db_block(data.cosmos_db_enabled, defaults),
        "",
        _document_intelligence_block(data.document_intelligence_enabled, env),
        "",
        f"  # Speech Services - MUST be present even if disabled (map(any) type constraint)",
        f"  speech_services = {{",
        f"    enabled = {'true' if data.speech_services_enabled else 'false'}",
        f"  }}",
        "",
        _log_analytics_block(defaults),
        "",
        _openai_block(data.openai_enabled, model_deployments, env),
        "",
        _apim_auth_block(data.apim_auth_mode),
        "",
        admin_block,
        "",
        _apim_policies_block(data),
        "",
        f"  # Per-tenant APIM Diagnostics - logs go to tenant's own LAW",
        f"  apim_diagnostics = {{",
        f"    sampling_percentage = 100",
        f'    verbosity           = "information"',
        f"  }}",
        f"}}",
    ]

    return "\n".join(lines) + "\n"


# ---- Block generators ----


def _key_vault_block(enabled: bool, defaults: dict) -> str:
    return "\n".join([
        f"  key_vault = {{",
        f"    enabled                    = {'true' if enabled else 'false'}",
        f'    sku                        = "standard"',
        f"    purge_protection_enabled   = true",
        f"    soft_delete_retention_days = {defaults['soft_delete_retention_days']}",
        f"  }}",
    ])


def _storage_account_block(enabled: bool, defaults: dict, env: str) -> str:
    lines = [
        f"  storage_account = {{",
        f"    enabled                  = {'true' if enabled else 'false'}",
        f'    account_tier             = "Standard"',
        f'    account_replication_type = "{defaults["replication_type"]}"',
        f'    account_kind             = "StorageV2"',
        f'    access_tier              = "Hot"',
    ]
    if env == "test":
        lines += [
            f"    diagnostics = {{",
            f"      log_groups        = []",
            f"      log_categories    = []",
            f'      metric_categories = ["Capacity", "Transaction"]',
            f"    }}",
        ]
    lines.append(f"  }}")
    return "\n".join(lines)


def _ai_search_block(enabled: bool) -> str:
    return "\n".join([
        f"  ai_search = {{",
        f"    enabled            = {'true' if enabled else 'false'}",
        f'    sku                = "basic"',
        f"    replica_count      = 1",
        f"    partition_count    = 1",
        f'    semantic_search    = "free"',
        f"    local_auth_enabled = true",
        f"  }}",
    ])


def _cosmos_db_block(enabled: bool, defaults: dict) -> str:
    lines = [
        f"  cosmos_db = {{",
        f"    enabled                      = {'true' if enabled else 'false'}",
        f'    offer_type                   = "Standard"',
        f'    kind                         = "GlobalDocumentDB"',
        f'    consistency_level            = "Session"',
        f"    max_interval_in_seconds      = 5",
        f"    max_staleness_prefix         = 100",
        f"    geo_redundant_backup_enabled = {'true' if defaults['geo_redundant_backup'] else 'false'}",
        f"    automatic_failover_enabled   = false",
        f"    total_throughput_limit       = 1000",
    ]
    if enabled:
        lines += [
            f'    database_name                = "default"',
            f'    container_name               = "cosmosContainer"',
        ]
    lines.append(f"  }}")
    return "\n".join(lines)


def _document_intelligence_block(enabled: bool, env: str) -> str:
    lines = [
        f"  document_intelligence = {{",
        f"    enabled = {'true' if enabled else 'false'}",
        f'    sku     = "S0"',
        f'    kind    = "FormRecognizer"',
    ]
    if env == "test":
        lines += [
            f"    diagnostics = {{",
            f'      log_groups        = ["allLogs"]',
            f"      log_categories    = []",
            f'      metric_categories = ["AllMetrics"]',
            f"    }}",
        ]
    lines.append(f"  }}")
    return "\n".join(lines)


def _log_analytics_block(defaults: dict) -> str:
    return "\n".join([
        f"  log_analytics = {{",
        f"    enabled        = true",
        f"    retention_days = {defaults['log_retention_days']}",
        f'    sku            = "PerGB2018"',
        f"  }}",
    ])


def _openai_block(enabled: bool, model_deployments: list[dict], env: str) -> str:
    lines = [
        f"  openai = {{",
        f"    enabled = {'true' if enabled else 'false'}",
        f'    sku     = "S0"',
    ]
    if env == "test":
        lines += [
            f"    diagnostics = {{",
            f'      log_groups        = ["allLogs"]',
            f"      log_categories    = []",
            f'      metric_categories = ["AllMetrics"]',
            f"    }}",
        ]

    if enabled and model_deployments:
        lines.append(f"    model_deployments = [")
        for i, m in enumerate(model_deployments):
            lines += [
                f"      {{",
                f'        name          = "{m["name"]}"',
                f'        model_name    = "{m["model_name"]}"',
                f'        model_version = "{m["model_version"]}"',
                f'        scale_type    = "{m["scale_type"]}"',
                f'        capacity      = {m["capacity"]}',
                f"      }},",
            ]
        lines.append(f"    ]")
    lines.append(f"  }}")
    return "\n".join(lines)


def _apim_auth_block(auth_mode: str) -> str:
    return "\n".join([
        f"  apim_auth = {{",
        f'    mode                 = "{auth_mode}"',
        f"    key_rotation_enabled = false",
        f"  }}",
    ])


def _build_user_management(admin_emails: list[str]) -> str:
    if not admin_emails:
        return "  user_management = {}"

    email_lines = ",\n".join(f'        "{e}"' for e in admin_emails)
    return "\n".join([
        f"  user_management = {{",
        f"    seed_members = {{",
        f"      admin = [",
        f"{email_lines}",
        f"      ]",
        f"    }}",
        f"  }}",
    ])


def _apim_policies_block(data: TenantFormData) -> str:
    return "\n".join([
        f"  apim_policies = {{",
        f"    rate_limiting = {{",
        f"      enabled           = {'true' if data.rate_limiting_enabled else 'false'}",
        f"      tokens_per_minute = {data.tokens_per_minute}",
        f"    }}",
        f"    pii_redaction = {{",
        f"      enabled     = {'true' if data.pii_redaction_enabled else 'false'}",
        f"      fail_closed = false",
        f"    }}",
        f"    usage_logging = {{",
        f"      enabled = {'true' if data.usage_logging_enabled else 'false'}",
        f"    }}",
        f"    streaming_metrics = {{",
        f"      enabled = true",
        f"    }}",
        f"    tracking_dimensions = {{",
        f"      enabled = true",
        f"    }}",
        f"    intelligent_routing = {{",
        f"      enabled = false",
        f"    }}",
        f"  }}",
    ])


def _build_model_deployments(families: list[str], capacity_tier: str) -> list[dict]:
    """Expand selected model families into individual deployment entries."""
    multiplier = CAPACITY_TIERS.get(capacity_tier, CAPACITY_TIERS["standard"])["multiplier"]
    deployments = []
    for family_key in families:
        family = MODEL_FAMILIES.get(family_key)
        if not family:
            continue
        for model in family["models"]:
            deployments.append({
                "name": model["name"],
                "model_name": model["model_name"],
                "model_version": model["model_version"],
                "scale_type": model["scale_type"],
                "capacity": max(1, int(model["default_capacity"] * multiplier)),
            })
    return deployments
