"""Generate tenant.tfvars HCL from form data for each environment.

The public entry point is :func:`generate_all_env_tfvars`, which accepts a
:class:`~src.models.tenant.TenantFormData` instance and returns a dict
mapping environment name to the full HCL string for that environment.

Design notes
------------
* All block-level helpers are private (``_``-prefixed) and produce a
  multi-line HCL string for a single ``tenant { ... }`` sub-block.
* ``ENV_DEFAULTS`` drives the env-specific differences (retention, SKUs,
  diagnostics). Add a new key here to fan it out to all environments.
* The generated HCL must remain consistent with the reference tenant in
  ``infra-ai-hub/params/test/tenants/``. When the Terraform schema changes,
  update :data:`ENV_DEFAULTS` and the affected block helpers.
* ``speech_services`` is *always* emitted (even when disabled) because the
  ``map(any)`` Terraform type requires every key present to avoid HCL type
  unification errors.
"""

from __future__ import annotations

from typing import Any

from src.models.form_schema import CAPACITY_TIERS, MODEL_FAMILIES
from src.models.tenant import TenantFormData

# Environment-specific overrides applied to every generated tfvars.
ENV_DEFAULTS: dict[str, dict[str, Any]] = {
    "dev": {
        "environment_tag": "dev",
        "soft_delete_retention_days": 7,
        "replication_type": "LRS",
        "geo_redundant_backup": False,
        "log_retention_days": 30,
    },
    "test": {
        "environment_tag": "test",
        "soft_delete_retention_days": 30,
        "replication_type": "LRS",
        "geo_redundant_backup": False,
        "log_retention_days": 30,
    },
    "prod": {
        "environment_tag": "prod",
        "soft_delete_retention_days": 90,
        "replication_type": "LRS",
        "geo_redundant_backup": False,
        "log_retention_days": 90,
    },
}


def generate_all_env_tfvars(data: TenantFormData) -> dict[str, str]:
    """Generate tenant.tfvars HCL for all three environments in one call.

    Parameters
    ----------
    data:
        Validated form data from :class:`~src.models.tenant.TenantFormData`.

    Returns
    -------
    dict[str, str]
        Mapping ``{"dev": "<hcl>", "test": "<hcl>", "prod": "<hcl>"}``.
        Each value is a complete, ready-to-write ``tenant.tfvars`` file.
    """
    return {env: _generate_tfvars(data, env) for env in ("dev", "test", "prod")}


def _generate_tfvars(data: TenantFormData, env: str) -> str:
    """Render a complete tenant.tfvars HCL string for a single environment.

    Assembles the top-level ``tenant { ... }`` block by delegating each
    sub-block to a dedicated helper.  Env-specific values (retention,
    diagnostics) are supplied via :data:`ENV_DEFAULTS`.

    Parameters
    ----------
    data:
        Validated :class:`~src.models.tenant.TenantFormData` instance.
    env:
        Target environment: ``"dev"``, ``"test"``, or ``"prod"``.

    Returns
    -------
    str
        Multi-line HCL string ready to be written to ``tenant.tfvars``.
    """
    defaults = ENV_DEFAULTS[env]
    env_label = env.upper()

    model_deployments = _build_model_deployments(data.model_families, data.capacity_tier)
    admin_block = _build_user_management(data.admin_emails)

    lines = [
        f"# =============================================================================",
        f"# TENANT: {data.display_name} - {env_label} ENVIRONMENT",
        f"# =============================================================================",
        f"# {env_label} environment configuration for {data.display_name}.",
        f"# Generated by Tenant Onboarding Portal.",
        f"# =============================================================================",
        f"",
        f'tenant = {{',
        f'  tenant_name  = "{data.project_name}"',
        f'  display_name = "{data.display_name}"',
        f'  enabled      = true',
        f"",
        f"  # PE subnet assignment — sticky, do not change after first deploy (destroys/recreates all PEs)",
        f'  # Valid keys: privateendpoints-subnet, privateendpoints-subnet-1, privateendpoints-subnet-2, ...',
        f'  pe_subnet_key = "privateendpoints-subnet"',
        f"",
        f"  tags = {{",
        f'    ministry    = "{data.ministry}"',
        f'    environment = "{defaults["environment_tag"]}"',
    ]
    if data.department:
        lines.append(f'    department  = "{data.department}"')
    lines += [
        f"  }}",
        f"",
        _key_vault_block(data.key_vault_enabled, defaults),
        "",
        _storage_account_block(data.storage_account_enabled, defaults, env),
        "",
        _ai_search_block(data.ai_search_enabled),
        "",
        _cosmos_db_block(data.cosmos_db_enabled, defaults),
        "",
        _document_intelligence_block(data.document_intelligence_enabled, env),
        "",
        f"  # Speech Services - MUST be present even if disabled (map(any) type constraint)",
        f"  speech_services = {{",
        f"    enabled = {'true' if data.speech_services_enabled else 'false'}",
        f"  }}",
        "",
        _log_analytics_block(defaults),
        "",
        _openai_block(data.openai_enabled, model_deployments, env),
        "",
        _apim_auth_block(data.apim_auth_mode),
        "",
        admin_block,
        "",
        _apim_policies_block(data),
        "",
        f"  # Per-tenant APIM Diagnostics - logs go to tenant's own LAW",
        f"  apim_diagnostics = {{",
        f"    sampling_percentage = 100",
        f'    verbosity           = "information"',
        f"  }}",
        f"}}",
    ]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Block generators — each returns a self-contained HCL string for one
# sub-block inside the tenant { ... } map.
# ---------------------------------------------------------------------------


def _key_vault_block(enabled: bool, defaults: dict) -> str:
    """Render the ``key_vault { ... }`` HCL sub-block.

    Parameters
    ----------
    enabled:
        Whether the Key Vault service is requested by the tenant.
    defaults:
        Env-specific defaults dict from :data:`ENV_DEFAULTS`.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    return "\n".join([
        f"  key_vault = {{",
        f"    enabled                    = {'true' if enabled else 'false'}",
        f'    sku                        = "standard"',
        f"    purge_protection_enabled   = true",
        f"    soft_delete_retention_days = {defaults['soft_delete_retention_days']}",
        f"  }}",
    ])


def _storage_account_block(enabled: bool, defaults: dict, env: str) -> str:
    """Render the ``storage_account { ... }`` HCL sub-block.

    Adds a ``diagnostics { ... }`` sub-block for ``test`` to enable capacity
    and transaction metrics.

    Parameters
    ----------
    enabled:
        Whether the Storage Account is requested.
    defaults:
        Env-specific defaults dict from :data:`ENV_DEFAULTS`.
    env:
        Target environment name. ``"test"`` adds a diagnostics block.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    lines = [
        f"  storage_account = {{",
        f"    enabled                  = {'true' if enabled else 'false'}",
        f'    account_tier             = "Standard"',
        f'    account_replication_type = "{defaults["replication_type"]}"',
        f'    account_kind             = "StorageV2"',
        f'    access_tier              = "Hot"',
    ]
    if env == "test":
        lines += [
            f"    diagnostics = {{",
            f"      log_groups        = []",
            f"      log_categories    = []",
            f'      metric_categories = ["Capacity", "Transaction"]',
            f"    }}",
        ]
    lines.append(f"  }}")
    return "\n".join(lines)


def _ai_search_block(enabled: bool) -> str:
    """Render the ``ai_search { ... }`` HCL sub-block.

    Parameters
    ----------
    enabled:
        Whether Azure AI Search is requested.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    return "\n".join([
        f"  ai_search = {{",
        f"    enabled            = {'true' if enabled else 'false'}",
        f'    sku                = "basic"',
        f"    replica_count      = 1",
        f"    partition_count    = 1",
        f'    semantic_search    = "free"',
        f"    local_auth_enabled = true",
        f"  }}",
    ])


def _cosmos_db_block(enabled: bool, defaults: dict) -> str:
    """Render the ``cosmos_db { ... }`` HCL sub-block.

    When enabled, adds ``database_name`` and ``container_name`` defaults.
    These attributes are omitted when disabled to avoid Terraform drift.

    Parameters
    ----------
    enabled:
        Whether Cosmos DB is requested.
    defaults:
        Env-specific defaults dict from :data:`ENV_DEFAULTS`.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    lines = [
        f"  cosmos_db = {{",
        f"    enabled                      = {'true' if enabled else 'false'}",
        f'    offer_type                   = "Standard"',
        f'    kind                         = "GlobalDocumentDB"',
        f'    consistency_level            = "Session"',
        f"    max_interval_in_seconds      = 5",
        f"    max_staleness_prefix         = 100",
        f"    geo_redundant_backup_enabled = {'true' if defaults['geo_redundant_backup'] else 'false'}",
        f"    automatic_failover_enabled   = false",
        f"    total_throughput_limit       = 1000",
    ]
    if enabled:
        lines += [
            f'    database_name                = "default"',
            f'    container_name               = "cosmosContainer"',
        ]
    lines.append(f"  }}")
    return "\n".join(lines)


def _document_intelligence_block(enabled: bool, env: str) -> str:
    """Render the ``document_intelligence { ... }`` HCL sub-block.

    Parameters
    ----------
    enabled:
        Whether Document Intelligence (Form Recognizer) is requested.
    env:
        Target environment name. ``"test"`` adds a diagnostics block.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    lines = [
        f"  document_intelligence = {{",
        f"    enabled = {'true' if enabled else 'false'}",
        f'    sku     = "S0"',
        f'    kind    = "FormRecognizer"',
    ]
    if env == "test":
        lines += [
            f"    diagnostics = {{",
            f'      log_groups        = ["allLogs"]',
            f"      log_categories    = []",
            f'      metric_categories = ["AllMetrics"]',
            f"    }}",
        ]
    lines.append(f"  }}")
    return "\n".join(lines)


def _log_analytics_block(defaults: dict) -> str:
    """Render the ``log_analytics { ... }`` HCL sub-block.

    Parameters
    ----------
    defaults:
        Env-specific defaults dict; ``log_retention_days`` is used.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    return "\n".join([
        f"  log_analytics = {{",
        f"    enabled        = true",
        f"    retention_days = {defaults['log_retention_days']}",
        f'    sku            = "PerGB2018"',
        f"  }}",
    ])


def _openai_block(enabled: bool, model_deployments: list[dict], env: str) -> str:
    """Render the ``openai { ... }`` HCL sub-block, including model deployments.

    When ``enabled`` is True and ``model_deployments`` is non-empty, a
    ``model_deployments = [ ... ]`` list is inlined. The ``test`` environment
    additionally includes a ``diagnostics { ... }`` sub-block.

    Parameters
    ----------
    enabled:
        Whether Azure OpenAI is requested.
    model_deployments:
        List of expanded deployment dicts from :func:`_build_model_deployments`.
    env:
        Target environment name.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    lines = [
        f"  openai = {{",
        f"    enabled = {'true' if enabled else 'false'}",
        f'    sku     = "S0"',
    ]
    if env == "test":
        lines += [
            f"    diagnostics = {{",
            f'      log_groups        = ["allLogs"]',
            f"      log_categories    = []",
            f'      metric_categories = ["AllMetrics"]',
            f"    }}",
        ]

    if enabled and model_deployments:
        lines.append(f"    model_deployments = [")
        for i, m in enumerate(model_deployments):
            lines += [
                f"      {{",
                f'        name          = "{m["name"]}"',
                f'        model_name    = "{m["model_name"]}"',
                f'        model_version = "{m["model_version"]}"',
                f'        scale_type    = "{m["scale_type"]}"',
                f'        capacity      = {m["capacity"]}',
                f"      }},",
            ]
        lines.append(f"    ]")
    lines.append(f"  }}")
    return "\n".join(lines)


def _apim_auth_block(auth_mode: str) -> str:
    """Render the ``apim_auth { ... }`` HCL sub-block.

    Parameters
    ----------
    auth_mode:
        Authentication mode: ``"subscription_key"`` or ``"oauth2"``.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    return "\n".join([
        f"  apim_auth = {{",
        f'    mode                 = "{auth_mode}"',
        f"    key_rotation_enabled = false",
        f"  }}",
    ])


def _build_user_management(admin_emails: list[str]) -> str:
    """Render the ``user_management { ... }`` HCL sub-block.

    When ``admin_emails`` is empty, an empty block is emitted to satisfy the
    ``map(any)`` type requirement.

    Parameters
    ----------
    admin_emails:
        List of @gov.bc.ca email addresses to seed as admin members.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    if not admin_emails:
        return "  user_management = {}"

    email_lines = ",\n".join(f'        "{e}"' for e in admin_emails)
    return "\n".join([
        f"  user_management = {{",
        f"    seed_members = {{",
        f"      admin = [",
        f"{email_lines}",
        f"      ]",
        f"    }}",
        f"  }}",
    ])


def _apim_policies_block(data: TenantFormData) -> str:
    """Render the ``apim_policies { ... }`` HCL sub-block.

    Covers rate-limiting, PII redaction, usage logging, streaming metrics,
    tracking dimensions, and intelligent routing.  All values come from the
    form data; defaults are supplied in :class:`~src.models.tenant.TenantFormData`.

    Parameters
    ----------
    data:
        The validated form data instance.

    Returns
    -------
    str
        Multi-line HCL block indented for the ``tenant {}`` context.
    """
    return "\n".join([
        f"  apim_policies = {{",
        f"    rate_limiting = {{",
        f"      enabled           = {'true' if data.rate_limiting_enabled else 'false'}",
        f"      tokens_per_minute = {data.tokens_per_minute}",
        f"    }}",
        f"    pii_redaction = {{",
        f"      enabled     = {'true' if data.pii_redaction_enabled else 'false'}",
        f"      fail_closed = false",
        f"    }}",
        f"    usage_logging = {{",
        f"      enabled = {'true' if data.usage_logging_enabled else 'false'}",
        f"    }}",
        f"    streaming_metrics = {{",
        f"      enabled = true",
        f"    }}",
        f"    tracking_dimensions = {{",
        f"      enabled = true",
        f"    }}",
        f"    intelligent_routing = {{",
        f"      enabled = false",
        f"    }}",
        f"  }}",
    ])


def _build_model_deployments(families: list[str], capacity_tier: str) -> list[dict]:
    """Expand selected model family keys into individual deployment entries.

    Each entry corresponds to one ``model_deployments`` item in the generated
    HCL.  Capacity is scaled by the tier multiplier from
    :data:`~src.models.form_schema.CAPACITY_TIERS` and clamped to a minimum
    of 1 PTU to prevent invalid zero-capacity deployments.

    Parameters
    ----------
    families:
        List of model family keys (e.g. ``["gpt-4.1", "embeddings"]``).
        Unknown keys are silently skipped.
    capacity_tier:
        Capacity tier key (``"reduced"``, ``"standard"``, ``"elevated"``).
        Defaults to ``"standard"`` if the key is not found.

    Returns
    -------
    list[dict]
        List of dicts with keys: ``name``, ``model_name``, ``model_version``,
        ``scale_type``, ``capacity``.
    """
    multiplier = CAPACITY_TIERS.get(capacity_tier, CAPACITY_TIERS["standard"])["multiplier"]
    deployments = []
    for family_key in families:
        family = MODEL_FAMILIES.get(family_key)
        if not family:
            continue
        for model in family["models"]:
            deployments.append({
                "name": model["name"],
                "model_name": model["model_name"],
                "model_version": model["model_version"],
                "scale_type": model["scale_type"],
                "capacity": max(1, int(model["default_capacity"] * multiplier)),
            })
    return deployments
