import { CAPACITY_TIERS, MODEL_FAMILIES } from '../models/form-schema';
import type { TenantFormData } from '../types';

/**
 * Escape a string value for safe interpolation inside HCL double-quoted strings.
 * Prevents injection of arbitrary HCL via crafted display_name / department values.
 *
 * @param value - The raw string to escape.
 * @returns The escaped string safe for embedding inside HCL double-quoted strings.
 */
function escapeHcl(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$');
}

const ENV_DEFAULTS = {
  dev: {
    environment_tag: 'dev',
    soft_delete_retention_days: 7,
    replication_type: 'LRS',
    geo_redundant_backup: false,
    log_retention_days: 30,
  },
  test: {
    environment_tag: 'test',
    soft_delete_retention_days: 30,
    replication_type: 'LRS',
    geo_redundant_backup: false,
    log_retention_days: 30,
  },
  prod: {
    environment_tag: 'prod',
    soft_delete_retention_days: 90,
    replication_type: 'LRS',
    geo_redundant_backup: false,
    log_retention_days: 90,
  },
} as const;

type EnvironmentName = keyof typeof ENV_DEFAULTS;

type ModelDeployment = {
  name: string;
  model_name: string;
  model_version: string;
  scale_type: string;
  capacity: number;
};

/**
 * Generates Terraform `.tfvars` content for all three environments (dev, test, prod).
 *
 * @param data - The validated tenant form submission.
 * @returns An object keyed by environment name, each containing the rendered HCL string.
 */
export function generateAllEnvTfvars(data: TenantFormData): Record<EnvironmentName, string> {
  return {
    dev: generateTfvars(data, 'dev'),
    test: generateTfvars(data, 'test'),
    prod: generateTfvars(data, 'prod'),
  };
}

/**
 * Renders the full `.tfvars` HCL content for a single environment.
 *
 * @param data - The validated tenant form submission.
 * @param env - The target environment (`dev`, `test`, or `prod`).
 * @returns The rendered HCL string for the given environment.
 */
function generateTfvars(data: TenantFormData, env: EnvironmentName): string {
  const defaults = ENV_DEFAULTS[env];
  const envLabel = env.toUpperCase();
  const modelDeployments = buildModelDeployments(data.model_families, data.capacity_tier);
  const adminBlock = buildUserManagement(data);

  const lines = [
    '# =============================================================================',
    `# TENANT: ${data.display_name} - ${envLabel} ENVIRONMENT`,
    '# =============================================================================',
    `# ${envLabel} environment configuration for ${data.display_name}.`,
    '# Generated by Tenant Onboarding Portal.',
    '# =============================================================================',
    '',
    'tenant = {',
    `  tenant_name  = "${escapeHcl(data.project_name)}"`,
    `  display_name = "${escapeHcl(data.display_name)}"`,
    '  enabled      = true',
    '',
    '  # PE subnet assignment - sticky, do not change after first deploy (destroys/recreates all PEs)',
    '  # Valid keys: privateendpoints-subnet, privateendpoints-subnet-1, privateendpoints-subnet-2, ...',
    '  pe_subnet_key = "privateendpoints-subnet"',
    '',
    '  tags = {',
    `    ministry    = "${escapeHcl(data.ministry)}"`,
    `    environment = "${defaults.environment_tag}"`,
  ];

  if (data.department) {
    lines.push(`    department  = "${escapeHcl(data.department)}"`);
  }

  lines.push(
    '  }',
    '',
    keyVaultBlock(data.key_vault_enabled, defaults),
    '',
    storageAccountBlock(data.storage_account_enabled, defaults, env),
    '',
    aiSearchBlock(data.ai_search_enabled),
    '',
    cosmosDbBlock(data.cosmos_db_enabled, defaults),
    '',
    documentIntelligenceBlock(data.document_intelligence_enabled, env),
    '',
    '  # Speech Services - MUST be present even if disabled (map(any) type constraint)',
    '  speech_services = {',
    `    enabled = ${data.speech_services_enabled ? 'true' : 'false'}`,
    '  }',
    '',
    logAnalyticsBlock(defaults),
    '',
    openAiBlock(data.openai_enabled, modelDeployments, env),
    '',
    adminBlock,
    '',
    apimPoliciesBlock(data),
    '',
    "  # Per-tenant APIM Diagnostics - logs go to tenant's own LAW",
    '  apim_diagnostics = {',
    '    sampling_percentage = 100',
    '    verbosity           = "information"',
    '  }',
    '}',
  );

  return `${lines.join('\n')}\n`;
}

/**
 * Builds the `key_vault` HCL block for a given environment.
 *
 * @param enabled - Whether Key Vault is enabled for this tenant.
 * @param defaults - The environment-specific default values.
 * @returns The `key_vault = { ... }` HCL block as a string.
 */
function keyVaultBlock(enabled: boolean, defaults: (typeof ENV_DEFAULTS)[EnvironmentName]): string {
  return [
    '  key_vault = {',
    `    enabled                    = ${enabled ? 'true' : 'false'}`,
    '    sku                        = "standard"',
    '    purge_protection_enabled   = true',
    `    soft_delete_retention_days = ${defaults.soft_delete_retention_days}`,
    '  }',
  ].join('\n');
}

/**
 * Builds the `storage_account` HCL block for a given environment.
 *
 * Includes diagnostics configuration when targeting the `test` environment.
 *
 * @param enabled - Whether the storage account is enabled for this tenant.
 * @param defaults - The environment-specific default values.
 * @param env - The target environment name used to conditionally add diagnostics.
 * @returns The `storage_account = { ... }` HCL block as a string.
 */
function storageAccountBlock(
  enabled: boolean,
  defaults: (typeof ENV_DEFAULTS)[EnvironmentName],
  env: EnvironmentName,
): string {
  const lines = [
    '  storage_account = {',
    `    enabled                  = ${enabled ? 'true' : 'false'}`,
    '    account_tier             = "Standard"',
    `    account_replication_type = "${defaults.replication_type}"`,
    '    account_kind             = "StorageV2"',
    '    access_tier              = "Hot"',
  ];

  if (env === 'test') {
    lines.push(
      '    diagnostics = {',
      '      log_groups        = []',
      '      log_categories    = []',
      '      metric_categories = ["Capacity", "Transaction"]',
      '    }',
    );
  }

  lines.push('  }');
  return lines.join('\n');
}

/**
 * Builds the `ai_search` HCL block for a given environment.
 *
 * @param enabled - Whether AI Search is enabled for this tenant.
 * @returns The `ai_search = { ... }` HCL block as a string.
 */
function aiSearchBlock(enabled: boolean): string {
  return [
    '  ai_search = {',
    `    enabled            = ${enabled ? 'true' : 'false'}`,
    '    sku                = "basic"',
    '    replica_count      = 1',
    '    partition_count    = 1',
    '    semantic_search    = "free"',
    '    local_auth_enabled = true',
    '  }',
  ].join('\n');
}

/**
 * Builds the `cosmos_db` HCL block for a given environment.
 *
 * When the Cosmos DB feature is enabled, adds database and container name settings.
 *
 * @param enabled - Whether Cosmos DB is enabled for this tenant.
 * @param defaults - The environment-specific default values.
 * @returns The `cosmos_db = { ... }` HCL block as a string.
 */
function cosmosDbBlock(enabled: boolean, defaults: (typeof ENV_DEFAULTS)[EnvironmentName]): string {
  const lines = [
    '  cosmos_db = {',
    `    enabled                      = ${enabled ? 'true' : 'false'}`,
    '    offer_type                   = "Standard"',
    '    kind                         = "GlobalDocumentDB"',
    '    consistency_level            = "Session"',
    '    max_interval_in_seconds      = 5',
    '    max_staleness_prefix         = 100',
    `    geo_redundant_backup_enabled = ${defaults.geo_redundant_backup ? 'true' : 'false'}`,
    '    automatic_failover_enabled   = false',
    '    total_throughput_limit       = 1000',
  ];

  if (enabled) {
    lines.push(
      '    database_name                = "default"',
      '    container_name               = "cosmosContainer"',
    );
  }

  lines.push('  }');
  return lines.join('\n');
}

/**
 * Builds the `document_intelligence` HCL block for a given environment.
 *
 * Includes diagnostics configuration when targeting the `test` environment.
 *
 * @param enabled - Whether Document Intelligence is enabled for this tenant.
 * @param env - The target environment name used to conditionally add diagnostics.
 * @returns The `document_intelligence = { ... }` HCL block as a string.
 */
function documentIntelligenceBlock(enabled: boolean, env: EnvironmentName): string {
  const lines = [
    '  document_intelligence = {',
    `    enabled = ${enabled ? 'true' : 'false'}`,
    '    sku     = "S0"',
    '    kind    = "FormRecognizer"',
  ];

  if (env === 'test') {
    lines.push(
      '    diagnostics = {',
      '      log_groups        = ["allLogs"]',
      '      log_categories    = []',
      '      metric_categories = ["AllMetrics"]',
      '    }',
    );
  }

  lines.push('  }');
  return lines.join('\n');
}

/**
 * Builds the `log_analytics` HCL block for a given environment.
 *
 * @param defaults - The environment-specific default values containing the log retention period.
 * @returns The `log_analytics = { ... }` HCL block as a string.
 */
function logAnalyticsBlock(defaults: (typeof ENV_DEFAULTS)[EnvironmentName]): string {
  return [
    '  log_analytics = {',
    '    enabled        = true',
    `    retention_days = ${defaults.log_retention_days}`,
    '    sku            = "PerGB2018"',
    '  }',
  ].join('\n');
}

/**
 * Builds the `openai` HCL block for a given environment.
 *
 * When enabled, includes model deployment entries and, in `test` environments, diagnostics.
 *
 * @param enabled - Whether OpenAI is enabled for this tenant.
 * @param modelDeployments - The list of model deployment configurations to embed.
 * @param env - The target environment name used to conditionally add diagnostics.
 * @returns The `openai = { ... }` HCL block as a string.
 */
function openAiBlock(
  enabled: boolean,
  modelDeployments: ModelDeployment[],
  env: EnvironmentName,
): string {
  const lines = [
    '  openai = {',
    `    enabled = ${enabled ? 'true' : 'false'}`,
    '    sku     = "S0"',
  ];

  if (env === 'test') {
    lines.push(
      '    diagnostics = {',
      '      log_groups        = ["allLogs"]',
      '      log_categories    = []',
      '      metric_categories = ["AllMetrics"]',
      '    }',
    );
  }

  if (enabled && modelDeployments.length > 0) {
    lines.push('    model_deployments = [');
    for (const deployment of modelDeployments) {
      lines.push(
        '      {',
        `        name          = "${deployment.name}"`,
        `        model_name    = "${deployment.model_name}"`,
        `        model_version = "${deployment.model_version}"`,
        `        scale_type    = "${deployment.scale_type}"`,
        `        capacity      = ${deployment.capacity}`,
        '      },',
      );
    }
    lines.push('    ]');
  }

  lines.push('  }');
  return lines.join('\n');
}

/**
 * Builds the `user_management` HCL block including all seed member role assignments.
 *
 * Returns an empty `user_management = {}` block when no users are specified in
 * any of the admin, write, or read role lists.
 *
 * @param data - The validated tenant form submission containing user role lists.
 * @returns The `user_management = { ... }` HCL block as a string.
 */
function buildUserManagement(data: TenantFormData): string {
  const adminUsers = data.admin_users ?? [];
  const writeUsers = data.write_users ?? [];
  const readUsers = data.read_users ?? [];
  const hasUsers = adminUsers.length > 0 || writeUsers.length > 0 || readUsers.length > 0;

  if (!hasUsers) {
    return '  user_management = {}';
  }

  const roleBlocks = [
    buildRoleBlock('admin', adminUsers),
    buildRoleBlock('write', writeUsers),
    buildRoleBlock('read', readUsers),
  ].filter(Boolean);

  return ['  user_management = {', '    seed_members = {', ...roleBlocks, '    }', '  }'].join(
    '\n',
  );
}

/**
 * Builds a single HCL role block listing the email addresses assigned to that role.
 *
 * Returns `null` when the email list is empty so the caller can filter out absent roles.
 *
 * @param role - The role name (e.g. `'admin'`, `'write'`, `'read'`).
 * @param emails - The list of email addresses to assign to the role.
 * @returns An HCL snippet for the role block, or `null` if no emails are provided.
 */
function buildRoleBlock(role: string, emails: string[]): string | null {
  if (emails.length === 0) {
    return null;
  }

  return [
    `      ${role} = [`,
    emails.map((email) => `        "${email}"`).join(',\n'),
    '      ]',
  ].join('\n');
}

/**
 * Builds the `apim_policies` HCL block encoding all APIM policy feature flags.
 *
 * @param data - The validated tenant form submission containing policy toggle values.
 * @returns The `apim_policies = { ... }` HCL block as a string.
 */
function apimPoliciesBlock(data: TenantFormData): string {
  return [
    '  apim_policies = {',
    '    pii_redaction = {',
    `      enabled     = ${data.pii_redaction_enabled ? 'true' : 'false'}`,
    '      fail_closed = false',
    '    }',
    '    usage_logging = {',
    `      enabled = ${data.logging_enabled ? 'true' : 'false'}`,
    '    }',
    '    custom_rai_filters = {',
    `      enabled = ${data.custom_rai_filters_enabled ? 'true' : 'false'}`,
    '    }',
    '    streaming_metrics = {',
    '      enabled = true',
    '    }',
    '    tracking_dimensions = {',
    '      enabled = true',
    '    }',
    '    intelligent_routing = {',
    '      enabled = false',
    '    }',
    '  }',
  ].join('\n');
}

/**
 * Derives the list of model deployment configurations from the selected model families
 * and capacity tier.
 *
 * Each model within each selected family is scaled by the tier multiplier, with a
 * minimum capacity of 1.
 *
 * @param families - The list of model family keys selected by the tenant (e.g. `['gpt4o']`).
 * @param capacityTier - The capacity tier key (e.g. `'standard'`, `'high'`).
 * @returns An array of deployment configuration objects ready for HCL serialisation.
 */
function buildModelDeployments(families: string[], capacityTier: string): ModelDeployment[] {
  const multiplier =
    CAPACITY_TIERS[capacityTier as keyof typeof CAPACITY_TIERS]?.multiplier ??
    CAPACITY_TIERS.standard.multiplier;
  const deployments: ModelDeployment[] = [];

  for (const familyKey of families) {
    const family = MODEL_FAMILIES[familyKey as keyof typeof MODEL_FAMILIES];
    if (!family) {
      continue;
    }

    for (const model of family.models) {
      deployments.push({
        name: model.name,
        model_name: model.model_name,
        model_version: model.model_version,
        scale_type: model.scale_type,
        capacity: Math.max(1, Math.trunc(model.default_capacity * multiplier)),
      });
    }
  }

  return deployments;
}
