# =============================================================================
# TENANT: BC Archeology Portal - TEST ENVIRONMENT
# =============================================================================
# TEST environment configuration for BC Archeology Portal.
# Generated by Tenant Onboarding Portal.
# =============================================================================

tenant = {
  tenant_name  = "bc-archeology-portal"
  display_name = "BC Archeology Portal"
  enabled      = true

  # PE subnet assignment - sticky, do not change after first deploy (destroys/recreates all PEs)
  # Valid keys: privateendpoints-subnet, privateendpoints-subnet-1, privateendpoints-subnet-2, ...
  pe_subnet_key = "privateendpoints-subnet"

  tags = {
    ministry    = "FOR"
    environment = "test"
    department  = "Archeology"
  }

  key_vault = {
    enabled                    = false
    sku                        = "standard"
    purge_protection_enabled   = true
    soft_delete_retention_days = 30
  }

  storage_account = {
    enabled                  = true
    account_tier             = "Standard"
    account_replication_type = "LRS"
    account_kind             = "StorageV2"
    access_tier              = "Hot"
    diagnostics = {
      log_groups        = []
      log_categories    = []
      metric_categories = ["Capacity", "Transaction"]
    }
  }

  ai_search = {
    enabled            = false
    sku                = "basic"
    replica_count      = 1
    partition_count    = 1
    semantic_search    = "free"
    local_auth_enabled = true
  }

  cosmos_db = {
    enabled                      = false
    offer_type                   = "Standard"
    kind                         = "GlobalDocumentDB"
    consistency_level            = "Session"
    max_interval_in_seconds      = 5
    max_staleness_prefix         = 100
    geo_redundant_backup_enabled = false
    automatic_failover_enabled   = false
    total_throughput_limit       = 1000
  }

  document_intelligence = {
    enabled = true
    sku     = "S0"
    kind    = "FormRecognizer"
    diagnostics = {
      log_groups        = ["allLogs"]
      log_categories    = []
      metric_categories = ["AllMetrics"]
    }
  }

  # Speech Services - MUST be present even if disabled (map(any) type constraint)
  speech_services = {
    enabled = false
  }

  log_analytics = {
    enabled        = true
    retention_days = 30
    sku            = "PerGB2018"
  }

  openai = {
    enabled = true
    sku     = "S0"
    diagnostics = {
      log_groups        = ["allLogs"]
      log_categories    = []
      metric_categories = ["AllMetrics"]
    }
    model_deployments = [
      {
        name          = "gpt-4.1"
        model_name    = "gpt-4.1"
        model_version = "2025-04-14"
        scale_type    = "GlobalStandard"
        capacity      = 300
      },
      {
        name          = "gpt-4.1-mini"
        model_name    = "gpt-4.1-mini"
        model_version = "2025-04-14"
        scale_type    = "GlobalStandard"
        capacity      = 1500
      },
      {
        name          = "gpt-4.1-nano"
        model_name    = "gpt-4.1-nano"
        model_version = "2025-04-14"
        scale_type    = "GlobalStandard"
        capacity      = 1500
      },
      {
        name          = "gpt-4o"
        model_name    = "gpt-4o"
        model_version = "2024-11-20"
        scale_type    = "GlobalStandard"
        capacity      = 300
      },
      {
        name          = "gpt-4o-mini"
        model_name    = "gpt-4o-mini"
        model_version = "2024-07-18"
        scale_type    = "GlobalStandard"
        capacity      = 1500
      },
      {
        name          = "text-embedding-ada-002"
        model_name    = "text-embedding-ada-002"
        model_version = "2"
        scale_type    = "GlobalStandard"
        capacity      = 100
      },
      {
        name          = "text-embedding-3-large"
        model_name    = "text-embedding-3-large"
        model_version = "1"
        scale_type    = "GlobalStandard"
        capacity      = 100
      },
      {
        name          = "text-embedding-3-small"
        model_name    = "text-embedding-3-small"
        model_version = "1"
        scale_type    = "GlobalStandard"
        capacity      = 100
      },
      {
        name          = "gpt-5-mini"
        model_name    = "gpt-5-mini"
        model_version = "2025-08-07"
        scale_type    = "GlobalStandard"
        capacity      = 100
      },
      {
        name          = "gpt-5-nano"
        model_name    = "gpt-5-nano"
        model_version = "2025-08-07"
        scale_type    = "GlobalStandard"
        capacity      = 1500
      },
    ]
  }

  user_management = {
    seed_members = {
      admin = [
        "micheal.w.wells@gov.bc.ca"
      ]
    }
  }

  apim_policies = {
    pii_redaction = {
      enabled     = true
      fail_closed = false
    }
    usage_logging = {
      enabled = true
    }
    custom_rai_filters = {
      enabled = false
    }
    streaming_metrics = {
      enabled = true
    }
    tracking_dimensions = {
      enabled = true
    }
    intelligent_routing = {
      enabled = false
    }
  }

  # Per-tenant APIM Diagnostics - logs go to tenant's own LAW
  apim_diagnostics = {
    sampling_percentage = 100
    verbosity           = "information"
  }
}
