name: Encrypt/Decrypt (GPG + Base64)
description: Encrypt+base64 encode, or base64 decode+decrypt, using a shared GPG passphrase.

inputs:
  mode:
    description: "Operation mode: encrypt or decrypt"
    required: true
    default: encrypt
  gpg_passphrase:
    description: "GPG passphrase used for symmetric encryption/decryption (pass via secrets)"
    required: true
  value:
    description: "Sensitive value to encrypt/decrypt"
    required: true

outputs:
  result:
    description: "Encrypted+base64 value (encrypt mode) or decrypted plaintext (decrypt mode)"
    value: ${{ steps.run.outputs.result }}

runs:
  using: composite
  steps:
    - id: run
      shell: bash
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
        INPUT_VALUE: ${{ inputs.value }}
      run: |
        set -euo pipefail

        MODE="${INPUT_MODE,,}"
        KEY="$INPUT_GPG_PASSPHRASE"
        VALUE="$INPUT_VALUE"

        if [[ -z "$KEY" ]]; then
          echo "gpg_passphrase input is empty/missing" >&2
          exit 1
        fi
        if [[ -z "$VALUE" ]]; then
          echo "value input is empty/missing" >&2
          exit 1
        fi

        # Avoid leaking passphrase/plaintext in logs.
        echo "::add-mask::$KEY"
        echo "::add-mask::$VALUE"

        b64() {
          if base64 --help 2>/dev/null | grep -q -- '-w'; then
            base64 -w0
          else
            base64 | tr -d '\n'
          fi
        }

        decrypt_b64_gpg() {
          local encoded="$1"
          printf '%s' "$encoded" \
            | tr -d '\r\n' \
            | base64 --decode \
            | gpg --batch --yes --pinentry-mode loopback --passphrase "$KEY" --decrypt --output -
        }

        RESULT=""
        case "$MODE" in
          encrypt)
            RESULT=$(printf '%s' "$VALUE" | gpg --batch --yes --pinentry-mode loopback --passphrase "$KEY" --symmetric --cipher-algo AES256 | b64)
            ;;
          decrypt)
            RESULT="$(decrypt_b64_gpg "$VALUE")"
            ;;
          *)
            echo "Invalid mode '$MODE' (expected encrypt|decrypt)" >&2
            exit 1
            ;;
        esac

        echo "::add-mask::$RESULT"
        echo "result=$RESULT" >> "$GITHUB_OUTPUT"
